version: 2.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
after_build:
- xcopy C:\projects\guistracini-mandae\GuiStracini.Mandae\bin\Release\*.* C:\projects\guistracini-mandae\src\
- rd /s /q C:\projects\guistracini-mandae\GuiStracini.Mandae\bin\Release\
- cd C:\projects\guistracini-mandae\
- 7z a -tzip -mx9 "GuiStracini.Mandae.v%APPVEYOR_BUILD_VERSION%.zip" src
artifacts:
- path: GuiStracini.Mandae.v%APPVEYOR_BUILD_VERSION%.zip
  name: ZipFile
deploy:
- provider: Environment
  name: NuGet
- provider: GitHub
  tag: $(appveyor_build_version)
  auth_token:
    secure: VgYYJdvNLy/n9/uxxlaF0bMpIIrVxCb+dGr66U9nWfPWSN2ySdfuilO8klAw0uvF
  force_update: true
  artifact: ZipFile